### ISSUE TITLE
[Bug] Overlapping placeholder intercom icon with Intercom widget

### ISSUE THREAD

**Issue by kinotto** [calibreapp/react-live-chat-loader#260]
### Describe the bug

The intercom chat widget and the intercom placeholder icon don't overlap perfectly when the widget loads.

### How To Reproduce

current environment

- nextjs v13.1.1
- react-live-chat-loader v2.8.1

there is no custom styling to the intercom icon

<LiveChatLoaderProvider providerKey={appConfig.IntercomChatbotID} provider="intercom">
   <Component {...pageProps} />
  <Intercom />
</LiveChatLoaderProvider>

### Screenshots

![image](https://user-images.githubusercontent.com/4570071/230363517-eeb8afb8-ce00-436c-b1be-b4669ff19e62.png)

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct

**Comment by benschwarz** [comment]
Hey @kinotto, thanks for logging. 

Were you able to resolve this issue since logging? 

The [Intercom demo](https://react-live-chat-loader.vercel.app/intercom) shows the Intercom widget without any overlap present, so I can only assume something else was at play in the scenario that you've screenshotted back in April. 

Do you have a reproduction available of this bug?

**Comment by kinotto** [comment]
Hi @benschwarz ,
As of today the issue is still present
i'm running 
- nextjs v13.1.1
- react-live-chat-loader v2.8.1

with no custom styling

when hovering over the icon for the first time you see the placeholder than it goes away in the subsequent interactions

https://github.com/calibreapp/react-live-chat-loader/assets/4570071/3f6bcaf1-9d8d-4916-ab60-7830fba34bdf

![image](https://github.com/calibreapp/react-live-chat-loader/assets/4570071/b4eb60ef-b94c-4c24-ac77-0a7f37c5ca36)

**Comment by amarnath-cohesive** [comment]
This bug is still there
