### ISSUE TITLE
Demo site broken?

### ISSUE THREAD

**Issue by paulirish** [calibreapp/react-live-chat-loader#32]
aren't i supposed to see something in the bottom right?

![image](https://user-images.githubusercontent.com/39191/81965573-16b4bf80-95cd-11ea-9e51-ff8266f9d674.png)

**Comment by thefoxis** [comment]
👋 @paulirish!

it's a fair expectation to see a demo straight away on the landing page. because we support several vendors, they all have separate pages with the widgets loaded, which you can find links to under `Intercom, Help Scout, Drift, and Facebook Messenger` copy.

I've made a note to make it more visually obvious where to find the demos. we'll tweak it soon enough :+1: thanks for pointing it out!
