### ISSUE TITLE
iOS: Intercom chat widget disappears after 6 seconds

### ISSUE THREAD

**Issue by statelessrich** [calibreapp/react-live-chat-loader#53]
I have the latest version installed and using Intercom via the instructions. On iOS Safari and Chrome, the placeholder Intercom chat widget appears but then disappears after about 6 seconds. Any idea why this is happening?

**Comment by benschwarz** [comment]
Hey @statelessrich

To me it sounds like the following:

- react-live-chat-loader is correctly implemented in your site (because as you've said, it displays successfully)
- the browser becomes idle, react-live-chat-loader calls for intercom to be loaded 
- some kind of error occurs and the intercom widget is not successfully initialised

To investigate further, I'd recommend checking the developer console for errors listed from intercom, as well as the network tab to confirm that intercom **is** loading resources. It might also be worthwhile to double check you've got the correct intercom app id. 

Hope that helps! If you do figure out what went wrong please leave an update here for anyone who comes across this issue ✌️

**Comment by statelessrich** [comment]
@benschwarz Thanks for the reply.
Looks like my setup was correct, and the issue was "visitor mode" being disabled in my Intercom settings.
